Simplify install, update and uninstall scripts

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,9 +1,8 @@
 #!/usr/bin/env bash
 
 # Check if git is available
-if ! command -v 'git' >/dev/null 2>&1; then
+if ! command -v 'git' >/dev/null; then
   echo 'Ooops, git not found.'
-  echo 'Go to https://git-scm.com for more info.'
   exit 1
 fi
 
@@ -13,24 +12,24 @@ remote_repo='https://github.com/adrfer/vim-oh-my.git'
 
 # Backup existing files, if any
 if [[ -d "${local_repo}" ]]; then
-  echo -n 'Backing up existing vim files...'
+  echo -n 'Backing up existing vim and tmux files...'
   mv -f "${local_repo%/}"{," copy $(date +%s)"}
   echo ' done.'
 fi
 
 # Download new files
-echo -n 'Downloading sassy configurations for the most iconic duo ever...'
+echo -n 'Downloading configurations for the most iconic duo ever...'
 
-if git clone --quiet "${remote_repo}" "${local_repo}" >/dev/null 2>&1; then
+if git clone "${remote_repo}" "${local_repo}" >/dev/null 2>&1; then
   echo ' done.'
 else
   echo
-  echo 'Ooops, there was an error, try again.'
+  echo "Ooops, unable to access ${remote_repo}, try again."o
   exit 1
 fi
 
 # Setup existing and new files
-echo -n 'Setting up resources files...'
+echo -n 'Setting up resource files...'
 ln -sf "${local_repo}/vimrc" "${HOME}/.vimrc" 
 ln -sf "${local_repo}/tmux.conf" "${HOME}/.tmux.conf"
 echo ' done.'
diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,9 +1,8 @@
 #!/usr/bin/env bash
 
 # Check if git is available
-if ! command -v 'git' >/dev/null 2>&1; then
+if ! command -v 'git' >/dev/null; then
   echo 'Ooops, git not found.'
-  echo 'Go to https://git-scm.com for more info.'
   exit 1
 fi
 
@@ -14,24 +13,24 @@ remote_repo='https://github.com/adrfer/vim-oh-my.git'
 # Update existing files or download new ones
 if [[ -d "${local_repo}" ]]; then
   cd "${local_repo}"
-  echo -n 'Updating sassy configurations for the most iconic duo ever...'
+  echo -n 'Updating configurations for the most iconic duo ever...'
 
-  if git checkout --quiet . >/dev/null 2>&1 && git pull --quiet origin master >/dev/null 2>&1; then
+  if git checkout . && git pull origin master >/dev/null 2>&1; then
+    cd - >/dev/null
     echo ' done.'
-    cd - >/dev/null 2>&1
   else
     echo
-    echo 'Ooops, there was an error, try again.'
+    echo "Ooops, unable to access ${remote_repo}, try again."
     exit 1
   fi
 else
-  echo -n 'Downloading sassy configurations for the most iconic duo ever...'
+  echo -n 'Downloading configurations for the most iconic duo ever...'
 
-  if git clone --quiet "${remote_repo}" "${local_repo}" >/dev/null 2>&1; then
+  if git clone "${remote_repo}" "${local_repo}" >/dev/null 2>&1; then
     echo ' done.'
   else
     echo
-    echo 'Ooops, there was an error, try again.'
+    echo "Ooops, unable to access ${remote_repo}, try again."
     exit 1
   fi
 fi
